[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pynnrtd"
authors = [{name = "Harsh Khilawala", email = "harshhkdev@gmail.com"}]
dynamic = ["version", "description"]
